### ISSUE TITLE
Quotes over ssh still not working

### ISSUE THREAD

**Issue by ebeigarts** [dokku/dokku#2322]
The issue seems to be the same as #345.
- `uname -a`: Linux 4.4.0-21-generic #37-Ubuntu SMP x86_64 (Ubuntu 16.04 LTS)
- `docker version`: 1.11.2
- `docker run -ti gliderlabs/herokuish:latest herokuish version`: not installed
- `dokku version`: 0.6.5

How was dokku installed?: `apt-get install dokku`

Actual Results:

``` bash
$ ssh -t dokku@example.com -- run myapp echo Hello
Hello

$ ssh -t dokku@example.com -- run myapp bash -c 'echo Hello'


$ ssh -t dokku@example.com -- run myapp bash -c "echo Hello"


$ ssh -t dokku@example.com -- run myapp 'bash -c "echo Hello"'
Hello": -c: line 0: unexpected EOF while looking for matching `"'
Hello": -c: line 1: syntax error: unexpected end of file

$ ssh -t dokku@example.com -- run myapp bash -c \"echo Hello\"
Hello": -c: line 0: unexpected EOF while looking for matching `"'
Hello": -c: line 1: syntax error: unexpected end of file
```

Expected Results:

``` bash
$ dokku run myapp echo Hello
Hello

$ dokku run myapp bash -c 'echo Hello'
Hello

$ dokku run myapp bash -c "echo Hello"
Hello
```

**Comment by josegonzalez** [comment]
Note: The last two examples of your "Expected Results" only work as expected when running for a dockerfile application. For herokuish applications, all commands are passed by the `/exec` binary (herokuish), which doesn't appear to support quotes in the way you'd want.

**Comment by StephanMeijer** [comment]
This problem still hasn't been fixed. Quotes are being ignored completely

**Comment by josegonzalez** [comment]
@StephanMeijer we're pretty well aware. Is this something you'd be interested in submitting a pull request to fix?

**Comment by StephanMeijer** [comment]
I'd willing to look into it tomorrow

**Comment by josegonzalez** [comment]
Feel free to submit a PR when ready, or ask questions in our slack channel.

**Comment by StephanMeijer** [comment]
I already fixed my issues on my side, so I am going to look into the fact I need it or not. 
What do you think what causes the problem?

**Comment by josegonzalez** [comment]
I've thought about this for a while, and my guess is that sshcommand is probably somehow mangling quotes. I would love if someone wanted to investigate in that direction :)

**Comment by aaronstillwell** [comment]
This should work fine. I'm seeing the same problem when trying to set backups on services. The correct approach AFAIK should to quote the entire string being passed to dokku.

The quotes don't show up below when not quoting the entire string, e.g
```
ssh -i ssh-key -p 3022 -v dokku@127.0.0.1 postgres:backup-schedule backup-testing "0 3 * * *" my-s3-bucket
...
debug1: Sending command: postgres:backup-schedule backup-testing 0 3 * * * my-s3-bucket
 !     Invalid flag provided, only '--use-iam' allowed
```

The below, correctly quoted string seems to be showing up correctly in the verbose SSH output. So I don't know why this still doesn't work.

```
ssh -i ssh-key -p 3022 -v dokku@127.0.0.1 postgres:backup-schedule 'backup-testing "0 3 * * *" my-s3-bucket'
...
debug1: Sending command: postgres:backup-schedule backup-testing "0 3 * * *" my-s3-bucket
 !     Invalid flag provided, only '--use-iam' allowed
```

I've tried duplicating some of the service plugin source in an attempt to replicate the issue independently of dokku but have as of yet not been able to.

**Comment by aaronstillwell** [comment]
I've added some debugging lines to the postgres plugin locally. It looks like despite the command looking fine in the SSH output, by the time it reaches the plugin, the quotes are passed directly as characters rather than being interpreted correctly.
```
debug1: Sending command: postgres:backup-schedule backup-testing "0 3 * * *" my-s3-bucket
args: postgres:backup-schedule backup-testing "0 3 * * *" my-s3-bucket
SERVICE: backup-testing
SCHEDULE: "0
BUCKET_NAME: 3
USE_IAM_OPTIONAL_FLAG: *
 !     Invalid flag provided, only '--use-iam' allowed
```

**Comment by aaronstillwell** [comment]
So the problem stems from using dokku as a forced command in the SSH config.

Note `ssh my-user@my-server 'postgres:backup-schedule backup-testing "0 3 * * *" my-s3-bucket'` will work, but using a dokku user e.g `ssh dokku@my-server 'postgres:backup-schedule backup-testing "0 3 * * *" my-s3-bucket'` will not.

Context: https://at.magma-soft.at/sw/blog/posts/The_Only_Way_For_SSH_Forced_Commands/

**Comment by josegonzalez** [comment]
So is using quotes just not possible due to using a forced command? If thats the case, we'll just need to close this and also update our docs somehow to point out this limitation.

**Comment by josegonzalez** [comment]
A maybe alternative would be to allow for decoding of arguments that have a prefix of `DOKKU_BASE64:`, and then encode everything in the official dokku client, but that doesn't lend itself well to folks who aren't using that client and either directly use ssh or have another client.

Also it's a bit silly.

**Comment by aaronstillwell** [comment]
Another complication of using a forced command seems to be that glob expansion happens _before_ the input hits our script? So e.g `ssh dokku@my-server 'postgres:backup-schedule backup-testing "0 3 * * *" my-s3-bucket'` becomes something akin to `postgres:backup-schedule backup-testing "0 3 file1 file2 file3 file4 *" my-s3-bucket` or whatever. 

I'll continue to research the issue as I do believe there's a fix/workaround here. Having to limit folks to log into the box adds potentially significant more config when compared with e.g using terraform to create the S3 buckets, set up dokku with bucket names, credentials etc per app.

**Comment by josegonzalez** [comment]
That expansion _shouldn't_ happen because you are using single-outer quotes.

**Comment by aaronstillwell** [comment]
So I finally have a workaround that fixes the issue for me.

Nevermind the expansion problem - this was due to where I was reading args (before dokku is invoked in an unquoted use of `$SSH_ORIGINAL_COMMAND`, see more below).

To debug this problem I've been hijacking the forced command with a bash script that does some pre-processing before calling dokku. So in `.sshcommand` I reference my own script `ssh-entry.sh` instead of dokku directly.

Here we can basically re-process the args and provide them, properly evaluated, to the dokku binary ourselves. E.g

```
#!/bin/bash

# $SSH_ORIGINAL_COMMAND is not parsed in the expected manner when it comes to
# handling quotes. We therefore use xargs here to come up with a correctly interpreted
# array of args, set those ourselves as arguments, then invoke dokku.
#
# SSH would not respect the quotes in the original command, e.g "0 4 * * *" would be interpreted
# as 5 different args:
# "0 4 * * *

readarray -t -O "${#arr[@]}" arr < <( printf '%s' "$SSH_ORIGINAL_COMMAND" | xargs -n 1 )

# Now we have the correct args in $arr, we can overrite the args $1, $2 etc
set -- "${arr[@]}"

# The dokku binary will read from SSH_ORIGINAL_COMMAND, which still has the incorrectly interpreted
# vars. As a hack we'll unset this - so to dokku we are effectively calling it the "traditional" way
# rather than from an SSH_ORIGINAL_COMMAND.
unset SSH_ORIGINAL_COMMAND

# Call dokku - the arguments are correct now!
dokku "$@"
```

I've verified that using this intermediate step, my issue is gone!

```
ssh -i ssh-key -p 3022 dokku@127.0.0.1 'postgres:backup-schedule backup-schedule "0 4 * * *" my-s3-bucket'
[DEBUG] SERVICE: backup-schedule
[DEBUG] SCHEDULE: 0 4 * * *
[DEBUG] BUCKET_NAME: my-s3-bucket
[DEBUG] USE_IAM_OPTIONAL_FLAG:
```

(Debugging logs are my own added to the postgres plugin)

So it looks like we probably need to do some of this preprocessing here? https://github.com/dokku/dokku/blob/547c14d18ea112b5fa9d1f55ea7a96e91d762c4e/dokku#L109-L122

I see xargs is already being used here (along with unquoted `$SSH_ORIGINAL_COMMAND` - maybe there lies some of my globbing problem?) but I'm fairly out of my depth here in regards to my bash foo, so could do with some guidance on implementation.

**Comment by josegonzalez** [comment]
Try modifying $SSH_ORIGINAL_COMMAND options right after line 110 and instead  pass "$@"?

**Comment by aaronstillwell** [comment]
@josegonzalez just returning to this... do you know why we only use xargs when using `config` or `docker-options` params?

```
if [[ -n "$SSH_ORIGINAL_COMMAND" ]]; then 
   export -n SSH_ORIGINAL_COMMAND 
   # shellcheck disable=SC2086 
   xargs $0 <<<$SSH_ORIGINAL_COMMAND 
   exit $? 
fi
```

I believe this would also work and seems to work for my use case w/ `postgres:backup-schedule` for example. But I'm not sure why we differentiate and don't want to break anything.

**Comment by aaronstillwell** [comment]
Looks like the initial fix for this problem didn't differentiate... https://github.com/dokku/dokku/pull/702/files so I'm assuming it was added for a reason (haven't read the follow-on conversation yet)

**Comment by aaronstillwell** [comment]
Here's the commit - but no explanation why https://github.com/dokku/dokku/pull/821/commits/67b7fa6263935e91bec734a12a1ca188f9b0f24d 

note those test cases seem to work for me locally even without the if statement

**Comment by josegonzalez** [comment]
@michaelshobbs do you remember why you made that change?

**Comment by josegonzalez** [comment]
@aaronstillwell sorry for returning so late to this.

Using the same parsing method in all places doesn't seem to work due to how the git plugin interacts with stuff, but we can just special-case that I think (see #6708 for details).

I've modified my PR (#6708) to take into account your change and we'll see if the existing tests pass. If they do, I'll create a dummy plugin subcommand for the [smoke-test-plugin](https://github.com/dokku/smoke-test-plugin) that validates the arguments come out as we want them.

**Comment by josegonzalez** [comment]
I think this works as expected following some local testing. Once the PR merges, we can tackle any follow-ups separately. Closing for now.
